import "./globals.css";
import { Inter } from "next/font/google";
import ThemeContextProvider from "../contexts/ThemeContextProvider";
import FolderIDContextProvider from "../contexts/FolderIDContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FolderIDContextProvider>
          <ThemeContextProvider>{children}</ThemeContextProvider>
        </FolderIDContextProvider>
      </body>
    </html>
  );
}
